export const PaymentEventType = {
  PAYMENT_REQUESTED: 'PAYMENT_REQUESTED',
  PAYMENT_CALLBACK_APPROVED: 'PAYMENT_CALLBACK_APPROVED',
  PAYMENT_APPROVED: 'PAYMENT_APPROVED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_POST_PROCESSING_FAILED: 'PAYMENT_POST_PROCESSING_FAILED',
  PAYMENT_REFUND_REQUESTED: 'PAYMENT_REFUND_REQUESTED',
  PAYMENT_REFUNDED: 'PAYMENT_REFUNDED',
  PAYMENT_REFUND_FAILED: 'PAYMENT_REFUND_FAILED',
} as const;

export type PaymentEventType = (typeof PaymentEventType)[keyof typeof PaymentEventType];
