export { AdminController } from './admin.controller';
export { AddressController } from './address.controller';
export { HealthController } from './health.controller';
export { MemberController } from './member.controller';
export { MovieController } from './movie.controller';
export { PaymentController } from './payment.controller';
export { ReservationController } from './reservation.controller';
export { SeatController } from './seat.controller';
export { TheaterController } from './theater.controller';
