export const DomainErrorCode = {
  INVALID_ADDRESS: 'INVALID_ADDRESS',
  INVALID_MEMBER_NAME: 'INVALID_MEMBER_NAME',
  INVALID_PHONE_NUMBER: 'INVALID_PHONE_NUMBER',
  INVALID_USER_ID: 'INVALID_USER_ID',
  INVALID_VERIFICATION_CODE: 'INVALID_VERIFICATION_CODE',
  PHONE_VERIFICATION_CODE_MISMATCH: 'PHONE_VERIFICATION_CODE_MISMATCH',
  PHONE_VERIFICATION_EXPIRED: 'PHONE_VERIFICATION_EXPIRED',
  PHONE_VERIFICATION_NOT_PENDING: 'PHONE_VERIFICATION_NOT_PENDING',
} as const;

export type DomainErrorCode = (typeof DomainErrorCode)[keyof typeof DomainErrorCode];
