import { Module } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import {
  ChangeMemberPasswordCommand,
  CancelReservationCommand,
  ConfirmPhoneVerificationCommand,
  CreateMovieCommand,
  CreateSeatHoldCommand,
  HandlePaymentCallbackCommand,
  IssueTemporaryPasswordCommand,
  LoginAdminCommand,
  LoginMemberCommand,
  LogoutMemberCommand,
  RecordAdminAuditCommand,
  RefreshMemberTokenCommand,
  ReleaseSeatHoldCommand,
  RefundPaymentCommand,
  RequestPhoneVerificationCommand,
  RequestPaymentCommand,
  SignupMemberCommand,
  WithdrawMemberCommand,
} from './dto';
import {
  ADMIN_AUDIT_REPOSITORY,
  CLOCK,
  LOG_EVENT_PUBLISHER,
  MEMBER_REPOSITORY,
  MOVIE_REPOSITORY,
  OPAQUE_TOKEN_GENERATOR,
  OUTBOX_EVENT_REPOSITORY,
  PASSWORD_HASHER,
  PAYMENT_CALLBACK_VERIFIER,
  PAYMENT_EVENT_LOG_REPOSITORY,
  PAYMENT_GATEWAY,
  PAYMENT_REQUEST_HASHER,
  PAYMENT_REPOSITORY,
  PHONE_VERIFICATION_REPOSITORY,
  RESERVATION_EVENT_REPOSITORY,
  RESERVATION_REPOSITORY,
  RESERVATION_SEAT_REPOSITORY,
  SEAT_HOLD_CACHE,
  SEAT_HOLD_LOCK,
  SEAT_HOLD_REPOSITORY,
  TEMPORARY_PASSWORD_GENERATOR,
  TOKEN_REPOSITORY,
  VERIFICATION_CODE_GENERATOR,
  type AdminAuditRepositoryPort,
  type ClockPort,
  type LogEventPublisherPort,
  type MemberRepositoryPort,
  type MovieRepositoryPort,
  type OpaqueTokenGeneratorPort,
  type OutboxEventRepositoryPort,
  type PasswordHasherPort,
  type PaymentCallbackVerifierPort,
  type PaymentEventLogRepositoryPort,
  type PaymentGatewayPort,
  type PaymentRequestHasherPort,
  type PaymentRepositoryPort,
  type PhoneVerificationRepositoryPort,
  type ReservationEventRepositoryPort,
  type ReservationRepositoryPort,
  type ReservationSeatRepositoryPort,
  type SeatHoldCachePort,
  type SeatHoldLockPort,
  type SeatHoldRepositoryPort,
  type TemporaryPasswordGeneratorPort,
  type TokenRepositoryPort,
  type VerificationCodeGeneratorPort,
} from '@application/commands/ports';
import { InfrastructureModule } from '@infrastructure';
import { ENV_KEY } from '@infrastructure/config';
import { CommandBus } from './command-bus';
import { TransactionalDecoratorProvider } from './transactional-decorator.provider';
import {
  ChangeMemberPasswordCommandHandler,
  CancelReservationCommandHandler,
  ConfirmPhoneVerificationCommandHandler,
  CreateMovieCommandHandler,
  CreateSeatHoldCommandHandler,
  HandlePaymentCallbackCommandHandler,
  IssueTemporaryPasswordCommandHandler,
  LoginAdminCommandHandler,
  LoginMemberCommandHandler,
  LogoutMemberCommandHandler,
  RecordAdminAuditCommandHandler,
  RefreshMemberTokenCommandHandler,
  ReleaseSeatHoldCommandHandler,
  RefundPaymentCommandHandler,
  RequestPhoneVerificationCommandHandler,
  RequestPaymentCommandHandler,
  SignupMemberCommandHandler,
  WithdrawMemberCommandHandler,
} from './handlers';

@Module({
  imports: [InfrastructureModule],
  providers: [
    TransactionalDecoratorProvider,
    {
      provide: RequestPhoneVerificationCommandHandler,
      useFactory: (
        phoneVerificationRepository: PhoneVerificationRepositoryPort,
        verificationCodeGenerator: VerificationCodeGeneratorPort,
        clock: ClockPort,
      ) =>
        new RequestPhoneVerificationCommandHandler(
          phoneVerificationRepository,
          verificationCodeGenerator,
          clock,
        ),
      inject: [PHONE_VERIFICATION_REPOSITORY, VERIFICATION_CODE_GENERATOR, CLOCK],
    },
    {
      provide: ConfirmPhoneVerificationCommandHandler,
      useFactory: (
        phoneVerificationRepository: PhoneVerificationRepositoryPort,
        clock: ClockPort,
      ) => new ConfirmPhoneVerificationCommandHandler(phoneVerificationRepository, clock),
      inject: [PHONE_VERIFICATION_REPOSITORY, CLOCK],
    },
    {
      provide: SignupMemberCommandHandler,
      useFactory: (
        memberRepository: MemberRepositoryPort,
        phoneVerificationRepository: PhoneVerificationRepositoryPort,
        passwordHasher: PasswordHasherPort,
        logEventPublisher: LogEventPublisherPort,
        clock: ClockPort,
      ) =>
        new SignupMemberCommandHandler(
          memberRepository,
          phoneVerificationRepository,
          passwordHasher,
          logEventPublisher,
          clock,
        ),
      inject: [
        MEMBER_REPOSITORY,
        PHONE_VERIFICATION_REPOSITORY,
        PASSWORD_HASHER,
        LOG_EVENT_PUBLISHER,
        CLOCK,
      ],
    },
    {
      provide: LoginMemberCommandHandler,
      useFactory: (
        memberRepository: MemberRepositoryPort,
        passwordHasher: PasswordHasherPort,
        clock: ClockPort,
        logEventPublisher: LogEventPublisherPort,
        opaqueTokenGenerator: OpaqueTokenGeneratorPort,
        tokenRepository: TokenRepositoryPort,
        configService: ConfigService,
      ) =>
        new LoginMemberCommandHandler(
          memberRepository,
          passwordHasher,
          clock,
          logEventPublisher,
          opaqueTokenGenerator,
          tokenRepository,
          {
            accessTokenTtlSeconds: configService.getOrThrow<number>(
              ENV_KEY.ACCESS_TOKEN_TTL_SECONDS,
            ),
            refreshTokenTtlSeconds: configService.getOrThrow<number>(
              ENV_KEY.REFRESH_TOKEN_TTL_SECONDS,
            ),
          },
        ),
      inject: [
        MEMBER_REPOSITORY,
        PASSWORD_HASHER,
        CLOCK,
        LOG_EVENT_PUBLISHER,
        OPAQUE_TOKEN_GENERATOR,
        TOKEN_REPOSITORY,
        ConfigService,
      ],
    },
    {
      provide: LoginAdminCommandHandler,
      useFactory: (
        opaqueTokenGenerator: OpaqueTokenGeneratorPort,
        tokenRepository: TokenRepositoryPort,
        clock: ClockPort,
        configService: ConfigService,
      ) =>
        new LoginAdminCommandHandler(
          opaqueTokenGenerator,
          tokenRepository,
          clock,
          {
            adminId: configService.getOrThrow<string>(ENV_KEY.ADMIN_USER_ID),
            password: configService.getOrThrow<string>(ENV_KEY.ADMIN_PASSWORD),
            accessTokenTtlSeconds: configService.getOrThrow<number>(
              ENV_KEY.ADMIN_ACCESS_TOKEN_TTL_SECONDS,
            ),
          },
        ),
      inject: [OPAQUE_TOKEN_GENERATOR, TOKEN_REPOSITORY, CLOCK, ConfigService],
    },
    {
      provide: RefreshMemberTokenCommandHandler,
      useFactory: (
        memberRepository: MemberRepositoryPort,
        opaqueTokenGenerator: OpaqueTokenGeneratorPort,
        tokenRepository: TokenRepositoryPort,
        clock: ClockPort,
        configService: ConfigService,
      ) =>
        new RefreshMemberTokenCommandHandler(
          memberRepository,
          opaqueTokenGenerator,
          tokenRepository,
          clock,
          {
            accessTokenTtlSeconds: configService.getOrThrow<number>(
              ENV_KEY.ACCESS_TOKEN_TTL_SECONDS,
            ),
            refreshTokenTtlSeconds: configService.getOrThrow<number>(
              ENV_KEY.REFRESH_TOKEN_TTL_SECONDS,
            ),
          },
        ),
      inject: [
        MEMBER_REPOSITORY,
        OPAQUE_TOKEN_GENERATOR,
        TOKEN_REPOSITORY,
        CLOCK,
        ConfigService,
      ],
    },
    {
      provide: IssueTemporaryPasswordCommandHandler,
      useFactory: (
        memberRepository: MemberRepositoryPort,
        phoneVerificationRepository: PhoneVerificationRepositoryPort,
        temporaryPasswordGenerator: TemporaryPasswordGeneratorPort,
        passwordHasher: PasswordHasherPort,
        clock: ClockPort,
      ) =>
        new IssueTemporaryPasswordCommandHandler(
          memberRepository,
          phoneVerificationRepository,
          temporaryPasswordGenerator,
          passwordHasher,
          clock,
        ),
      inject: [
        MEMBER_REPOSITORY,
        PHONE_VERIFICATION_REPOSITORY,
        TEMPORARY_PASSWORD_GENERATOR,
        PASSWORD_HASHER,
        CLOCK,
      ],
    },
    {
      provide: ChangeMemberPasswordCommandHandler,
      useFactory: (
        memberRepository: MemberRepositoryPort,
        passwordHasher: PasswordHasherPort,
        clock: ClockPort,
        logEventPublisher: LogEventPublisherPort,
      ) =>
        new ChangeMemberPasswordCommandHandler(
          memberRepository,
          passwordHasher,
          clock,
          logEventPublisher,
        ),
      inject: [MEMBER_REPOSITORY, PASSWORD_HASHER, CLOCK, LOG_EVENT_PUBLISHER],
    },
    {
      provide: WithdrawMemberCommandHandler,
      useFactory: (
        memberRepository: MemberRepositoryPort,
        tokenRepository: TokenRepositoryPort,
        clock: ClockPort,
        logEventPublisher: LogEventPublisherPort,
      ) =>
        new WithdrawMemberCommandHandler(
          memberRepository,
          tokenRepository,
          clock,
          logEventPublisher,
        ),
      inject: [MEMBER_REPOSITORY, TOKEN_REPOSITORY, CLOCK, LOG_EVENT_PUBLISHER],
    },
    {
      provide: LogoutMemberCommandHandler,
      useFactory: (
        tokenRepository: TokenRepositoryPort,
        clock: ClockPort,
      ) => new LogoutMemberCommandHandler(tokenRepository, clock),
      inject: [TOKEN_REPOSITORY, CLOCK],
    },
    {
      provide: RecordAdminAuditCommandHandler,
      useFactory: (adminAuditRepository: AdminAuditRepositoryPort) =>
        new RecordAdminAuditCommandHandler(adminAuditRepository),
      inject: [ADMIN_AUDIT_REPOSITORY],
    },
    {
      provide: CreateMovieCommandHandler,
      useFactory: (movieRepository: MovieRepositoryPort) =>
        new CreateMovieCommandHandler(movieRepository),
      inject: [MOVIE_REPOSITORY],
    },
    {
      provide: CreateSeatHoldCommandHandler,
      useFactory: (
        seatHoldRepository: SeatHoldRepositoryPort,
        seatHoldCache: SeatHoldCachePort,
        seatHoldLock: SeatHoldLockPort,
        clock: ClockPort,
        configService: ConfigService,
      ) =>
        new CreateSeatHoldCommandHandler(
          seatHoldRepository,
          seatHoldCache,
          seatHoldLock,
          clock,
          {
            ttlSeconds: configService.getOrThrow<number>(ENV_KEY.SEAT_HOLD_TTL_SECONDS),
          },
        ),
      inject: [
        SEAT_HOLD_REPOSITORY,
        SEAT_HOLD_CACHE,
        SEAT_HOLD_LOCK,
        CLOCK,
        ConfigService,
      ],
    },
    {
      provide: ReleaseSeatHoldCommandHandler,
      useFactory: (
        seatHoldRepository: SeatHoldRepositoryPort,
        seatHoldCache: SeatHoldCachePort,
      ) => new ReleaseSeatHoldCommandHandler(seatHoldRepository, seatHoldCache),
      inject: [SEAT_HOLD_REPOSITORY, SEAT_HOLD_CACHE],
    },
    {
      provide: RequestPaymentCommandHandler,
      useFactory: (
        paymentRepository: PaymentRepositoryPort,
        seatHoldRepository: SeatHoldRepositoryPort,
        paymentEventLogRepository: PaymentEventLogRepositoryPort,
        outboxEventRepository: OutboxEventRepositoryPort,
        paymentRequestHasher: PaymentRequestHasherPort,
        clock: ClockPort,
      ) =>
        new RequestPaymentCommandHandler(
          paymentRepository,
          seatHoldRepository,
          paymentEventLogRepository,
          outboxEventRepository,
          paymentRequestHasher,
          clock,
        ),
      inject: [
        PAYMENT_REPOSITORY,
        SEAT_HOLD_REPOSITORY,
        PAYMENT_EVENT_LOG_REPOSITORY,
        OUTBOX_EVENT_REPOSITORY,
        PAYMENT_REQUEST_HASHER,
        CLOCK,
      ],
    },
    {
      provide: HandlePaymentCallbackCommandHandler,
      useFactory: (
        paymentRepository: PaymentRepositoryPort,
        seatHoldRepository: SeatHoldRepositoryPort,
        reservationRepository: ReservationRepositoryPort,
        reservationSeatRepository: ReservationSeatRepositoryPort,
        reservationEventRepository: ReservationEventRepositoryPort,
        paymentEventLogRepository: PaymentEventLogRepositoryPort,
        outboxEventRepository: OutboxEventRepositoryPort,
        paymentCallbackVerifier: PaymentCallbackVerifierPort,
        clock: ClockPort,
      ) =>
        new HandlePaymentCallbackCommandHandler(
          paymentRepository,
          seatHoldRepository,
          reservationRepository,
          reservationSeatRepository,
          reservationEventRepository,
          paymentEventLogRepository,
          outboxEventRepository,
          paymentCallbackVerifier,
          clock,
        ),
      inject: [
        PAYMENT_REPOSITORY,
        SEAT_HOLD_REPOSITORY,
        RESERVATION_REPOSITORY,
        RESERVATION_SEAT_REPOSITORY,
        RESERVATION_EVENT_REPOSITORY,
        PAYMENT_EVENT_LOG_REPOSITORY,
        OUTBOX_EVENT_REPOSITORY,
        PAYMENT_CALLBACK_VERIFIER,
        CLOCK,
      ],
    },
    {
      provide: RefundPaymentCommandHandler,
      useFactory: (
        paymentRepository: PaymentRepositoryPort,
        paymentEventLogRepository: PaymentEventLogRepositoryPort,
        paymentGateway: PaymentGatewayPort,
        clock: ClockPort,
      ) =>
        new RefundPaymentCommandHandler(
          paymentRepository,
          paymentEventLogRepository,
          paymentGateway,
          clock,
        ),
      inject: [PAYMENT_REPOSITORY, PAYMENT_EVENT_LOG_REPOSITORY, PAYMENT_GATEWAY, CLOCK],
    },
    {
      provide: CancelReservationCommandHandler,
      useFactory: (
        reservationRepository: ReservationRepositoryPort,
        paymentRepository: PaymentRepositoryPort,
        reservationEventRepository: ReservationEventRepositoryPort,
        paymentEventLogRepository: PaymentEventLogRepositoryPort,
        outboxEventRepository: OutboxEventRepositoryPort,
        clock: ClockPort,
      ) =>
        new CancelReservationCommandHandler(
          reservationRepository,
          paymentRepository,
          reservationEventRepository,
          paymentEventLogRepository,
          outboxEventRepository,
          clock,
        ),
      inject: [
        RESERVATION_REPOSITORY,
        PAYMENT_REPOSITORY,
        RESERVATION_EVENT_REPOSITORY,
        PAYMENT_EVENT_LOG_REPOSITORY,
        OUTBOX_EVENT_REPOSITORY,
        CLOCK,
      ],
    },
    {
      provide: CommandBus,
      useFactory: (
        requestPhoneVerificationCommandHandler: RequestPhoneVerificationCommandHandler,
        confirmPhoneVerificationCommandHandler: ConfirmPhoneVerificationCommandHandler,
        signupMemberCommandHandler: SignupMemberCommandHandler,
        loginAdminCommandHandler: LoginAdminCommandHandler,
        loginMemberCommandHandler: LoginMemberCommandHandler,
        logoutMemberCommandHandler: LogoutMemberCommandHandler,
        recordAdminAuditCommandHandler: RecordAdminAuditCommandHandler,
        refreshMemberTokenCommandHandler: RefreshMemberTokenCommandHandler,
        issueTemporaryPasswordCommandHandler: IssueTemporaryPasswordCommandHandler,
        changeMemberPasswordCommandHandler: ChangeMemberPasswordCommandHandler,
        withdrawMemberCommandHandler: WithdrawMemberCommandHandler,
        createMovieCommandHandler: CreateMovieCommandHandler,
        createSeatHoldCommandHandler: CreateSeatHoldCommandHandler,
        releaseSeatHoldCommandHandler: ReleaseSeatHoldCommandHandler,
        requestPaymentCommandHandler: RequestPaymentCommandHandler,
        handlePaymentCallbackCommandHandler: HandlePaymentCallbackCommandHandler,
        refundPaymentCommandHandler: RefundPaymentCommandHandler,
        cancelReservationCommandHandler: CancelReservationCommandHandler,
      ) =>
        CommandBus.of([
          { command: RequestPhoneVerificationCommand, handler: requestPhoneVerificationCommandHandler },
          { command: ConfirmPhoneVerificationCommand, handler: confirmPhoneVerificationCommandHandler },
          { command: SignupMemberCommand, handler: signupMemberCommandHandler },
          { command: LoginAdminCommand, handler: loginAdminCommandHandler },
          { command: LoginMemberCommand, handler: loginMemberCommandHandler },
          { command: LogoutMemberCommand, handler: logoutMemberCommandHandler },
          { command: RecordAdminAuditCommand, handler: recordAdminAuditCommandHandler },
          { command: RefreshMemberTokenCommand, handler: refreshMemberTokenCommandHandler },
          { command: IssueTemporaryPasswordCommand, handler: issueTemporaryPasswordCommandHandler },
          { command: ChangeMemberPasswordCommand, handler: changeMemberPasswordCommandHandler },
          { command: WithdrawMemberCommand, handler: withdrawMemberCommandHandler },
          { command: CreateMovieCommand, handler: createMovieCommandHandler },
          { command: CreateSeatHoldCommand, handler: createSeatHoldCommandHandler },
          { command: ReleaseSeatHoldCommand, handler: releaseSeatHoldCommandHandler },
          { command: RequestPaymentCommand, handler: requestPaymentCommandHandler },
          { command: HandlePaymentCallbackCommand, handler: handlePaymentCallbackCommandHandler },
          { command: RefundPaymentCommand, handler: refundPaymentCommandHandler },
          { command: CancelReservationCommand, handler: cancelReservationCommandHandler },
        ]),
      inject: [
        RequestPhoneVerificationCommandHandler,
        ConfirmPhoneVerificationCommandHandler,
        SignupMemberCommandHandler,
        LoginAdminCommandHandler,
        LoginMemberCommandHandler,
        LogoutMemberCommandHandler,
        RecordAdminAuditCommandHandler,
        RefreshMemberTokenCommandHandler,
        IssueTemporaryPasswordCommandHandler,
        ChangeMemberPasswordCommandHandler,
        WithdrawMemberCommandHandler,
        CreateMovieCommandHandler,
        CreateSeatHoldCommandHandler,
        ReleaseSeatHoldCommandHandler,
        RequestPaymentCommandHandler,
        HandlePaymentCallbackCommandHandler,
        RefundPaymentCommandHandler,
        CancelReservationCommandHandler,
      ],
    },
  ],
  exports: [CommandBus],
})
export class CommandModule {}
