import { Module } from '@nestjs/common';
import {
  ChangeMemberPasswordCommand,
  CommandBus,
  ConfirmPhoneVerificationCommand,
  CreateSeatHoldCommand,
  HandlePaymentCallbackCommand,
  IssueTemporaryPasswordCommand,
  LoginMemberCommand,
  ReleaseSeatHoldCommand,
  RefundPaymentCommand,
  RequestPhoneVerificationCommand,
  RequestPaymentCommand,
  SignupMemberCommand,
} from '@application';
import {
  CLOCK,
  LOG_EVENT_PUBLISHER,
  MEMBER_REPOSITORY,
  OUTBOX_EVENT_REPOSITORY,
  PASSWORD_HASHER,
  PAYMENT_CALLBACK_VERIFIER,
  PAYMENT_EVENT_LOG_REPOSITORY,
  PAYMENT_GATEWAY,
  PAYMENT_REPOSITORY,
  PHONE_VERIFICATION_REPOSITORY,
  RESERVATION_EVENT_REPOSITORY,
  RESERVATION_REPOSITORY,
  RESERVATION_SEAT_REPOSITORY,
  SEAT_HOLD_CACHE,
  SEAT_HOLD_LOCK,
  SEAT_HOLD_REPOSITORY,
  TEMPORARY_PASSWORD_GENERATOR,
  TRANSACTION_MANAGER,
  VERIFICATION_CODE_GENERATOR,
  type ClockPort,
  type LogEventPublisherPort,
  type MemberRepositoryPort,
  type OutboxEventRepositoryPort,
  type PasswordHasherPort,
  type PaymentCallbackVerifierPort,
  type PaymentEventLogRepositoryPort,
  type PaymentGatewayPort,
  type PaymentRepositoryPort,
  type PhoneVerificationRepositoryPort,
  type ReservationEventRepositoryPort,
  type ReservationRepositoryPort,
  type ReservationSeatRepositoryPort,
  type SeatHoldCachePort,
  type SeatHoldLockPort,
  type SeatHoldRepositoryPort,
  type TemporaryPasswordGeneratorPort,
  type TransactionManagerPort,
  type VerificationCodeGeneratorPort,
} from '@application/commands/ports';
import { InfrastructureModule } from '@infrastructure';
import {
  ChangeMemberPasswordCommandHandler,
  ConfirmPhoneVerificationCommandHandler,
  CreateSeatHoldCommandHandler,
  HandlePaymentCallbackCommandHandler,
  IssueTemporaryPasswordCommandHandler,
  LoginMemberCommandHandler,
  ReleaseSeatHoldCommandHandler,
  RefundPaymentCommandHandler,
  RequestPhoneVerificationCommandHandler,
  RequestPaymentCommandHandler,
  SignupMemberCommandHandler,
} from './handlers';

@Module({
  imports: [InfrastructureModule],
  providers: [
    {
      provide: RequestPhoneVerificationCommandHandler,
      useFactory: (
        phoneVerificationRepository: PhoneVerificationRepositoryPort,
        verificationCodeGenerator: VerificationCodeGeneratorPort,
        clock: ClockPort,
      ) => new RequestPhoneVerificationCommandHandler(phoneVerificationRepository, verificationCodeGenerator, clock),
      inject: [PHONE_VERIFICATION_REPOSITORY, VERIFICATION_CODE_GENERATOR, CLOCK],
    },
    {
      provide: ConfirmPhoneVerificationCommandHandler,
      useFactory: (
        phoneVerificationRepository: PhoneVerificationRepositoryPort,
        clock: ClockPort,
      ) => new ConfirmPhoneVerificationCommandHandler(phoneVerificationRepository, clock),
      inject: [PHONE_VERIFICATION_REPOSITORY, CLOCK],
    },
    {
      provide: SignupMemberCommandHandler,
      useFactory: (
        memberRepository: MemberRepositoryPort,
        phoneVerificationRepository: PhoneVerificationRepositoryPort,
        passwordHasher: PasswordHasherPort,
        logEventPublisher: LogEventPublisherPort,
        clock: ClockPort,
      ) =>
        new SignupMemberCommandHandler(
          memberRepository,
          phoneVerificationRepository,
          passwordHasher,
          logEventPublisher,
          clock,
        ),
      inject: [MEMBER_REPOSITORY, PHONE_VERIFICATION_REPOSITORY, PASSWORD_HASHER, LOG_EVENT_PUBLISHER, CLOCK],
    },
    {
      provide: LoginMemberCommandHandler,
      useFactory: (
        memberRepository: MemberRepositoryPort,
        passwordHasher: PasswordHasherPort,
        clock: ClockPort,
        logEventPublisher: LogEventPublisherPort,
      ) => new LoginMemberCommandHandler(memberRepository, passwordHasher, clock, logEventPublisher),
      inject: [MEMBER_REPOSITORY, PASSWORD_HASHER, CLOCK, LOG_EVENT_PUBLISHER],
    },
    {
      provide: IssueTemporaryPasswordCommandHandler,
      useFactory: (
        memberRepository: MemberRepositoryPort,
        phoneVerificationRepository: PhoneVerificationRepositoryPort,
        temporaryPasswordGenerator: TemporaryPasswordGeneratorPort,
        passwordHasher: PasswordHasherPort,
        clock: ClockPort,
      ) =>
        new IssueTemporaryPasswordCommandHandler(
          memberRepository,
          phoneVerificationRepository,
          temporaryPasswordGenerator,
          passwordHasher,
          clock,
        ),
      inject: [
        MEMBER_REPOSITORY,
        PHONE_VERIFICATION_REPOSITORY,
        TEMPORARY_PASSWORD_GENERATOR,
        PASSWORD_HASHER,
        CLOCK,
      ],
    },
    {
      provide: ChangeMemberPasswordCommandHandler,
      useFactory: (
        memberRepository: MemberRepositoryPort,
        passwordHasher: PasswordHasherPort,
        clock: ClockPort,
        logEventPublisher: LogEventPublisherPort,
      ) => new ChangeMemberPasswordCommandHandler(memberRepository, passwordHasher, clock, logEventPublisher),
      inject: [MEMBER_REPOSITORY, PASSWORD_HASHER, CLOCK, LOG_EVENT_PUBLISHER],
    },
    {
      provide: CreateSeatHoldCommandHandler,
      useFactory: (
        seatHoldRepository: SeatHoldRepositoryPort,
        seatHoldCache: SeatHoldCachePort,
        seatHoldLock: SeatHoldLockPort,
        clock: ClockPort,
      ) => new CreateSeatHoldCommandHandler(seatHoldRepository, seatHoldCache, seatHoldLock, clock),
      inject: [SEAT_HOLD_REPOSITORY, SEAT_HOLD_CACHE, SEAT_HOLD_LOCK, CLOCK],
    },
    {
      provide: ReleaseSeatHoldCommandHandler,
      useFactory: (
        seatHoldRepository: SeatHoldRepositoryPort,
        seatHoldCache: SeatHoldCachePort,
      ) => new ReleaseSeatHoldCommandHandler(seatHoldRepository, seatHoldCache),
      inject: [SEAT_HOLD_REPOSITORY, SEAT_HOLD_CACHE],
    },
    {
      provide: RequestPaymentCommandHandler,
      useFactory: (
        paymentRepository: PaymentRepositoryPort,
        seatHoldRepository: SeatHoldRepositoryPort,
        paymentEventLogRepository: PaymentEventLogRepositoryPort,
        outboxEventRepository: OutboxEventRepositoryPort,
        transactionManager: TransactionManagerPort,
        clock: ClockPort,
      ) =>
        new RequestPaymentCommandHandler(
          paymentRepository,
          seatHoldRepository,
          paymentEventLogRepository,
          outboxEventRepository,
          transactionManager,
          clock,
        ),
      inject: [
        PAYMENT_REPOSITORY,
        SEAT_HOLD_REPOSITORY,
        PAYMENT_EVENT_LOG_REPOSITORY,
        OUTBOX_EVENT_REPOSITORY,
        TRANSACTION_MANAGER,
        CLOCK,
      ],
    },
    {
      provide: HandlePaymentCallbackCommandHandler,
      useFactory: (
        paymentRepository: PaymentRepositoryPort,
        seatHoldRepository: SeatHoldRepositoryPort,
        reservationRepository: ReservationRepositoryPort,
        reservationSeatRepository: ReservationSeatRepositoryPort,
        reservationEventRepository: ReservationEventRepositoryPort,
        paymentEventLogRepository: PaymentEventLogRepositoryPort,
        outboxEventRepository: OutboxEventRepositoryPort,
        paymentCallbackVerifier: PaymentCallbackVerifierPort,
        transactionManager: TransactionManagerPort,
        clock: ClockPort,
      ) =>
        new HandlePaymentCallbackCommandHandler(
          paymentRepository,
          seatHoldRepository,
          reservationRepository,
          reservationSeatRepository,
          reservationEventRepository,
          paymentEventLogRepository,
          outboxEventRepository,
          paymentCallbackVerifier,
          transactionManager,
          clock,
        ),
      inject: [
        PAYMENT_REPOSITORY,
        SEAT_HOLD_REPOSITORY,
        RESERVATION_REPOSITORY,
        RESERVATION_SEAT_REPOSITORY,
        RESERVATION_EVENT_REPOSITORY,
        PAYMENT_EVENT_LOG_REPOSITORY,
        OUTBOX_EVENT_REPOSITORY,
        PAYMENT_CALLBACK_VERIFIER,
        TRANSACTION_MANAGER,
        CLOCK,
      ],
    },
    {
      provide: RefundPaymentCommandHandler,
      useFactory: (
        paymentRepository: PaymentRepositoryPort,
        paymentEventLogRepository: PaymentEventLogRepositoryPort,
        paymentGateway: PaymentGatewayPort,
        transactionManager: TransactionManagerPort,
        clock: ClockPort,
      ) =>
        new RefundPaymentCommandHandler(
          paymentRepository,
          paymentEventLogRepository,
          paymentGateway,
          transactionManager,
          clock,
        ),
      inject: [PAYMENT_REPOSITORY, PAYMENT_EVENT_LOG_REPOSITORY, PAYMENT_GATEWAY, TRANSACTION_MANAGER, CLOCK],
    },
    {
      provide: CommandBus,
      useFactory: (
        requestPhoneVerificationCommandHandler: RequestPhoneVerificationCommandHandler,
        confirmPhoneVerificationCommandHandler: ConfirmPhoneVerificationCommandHandler,
        signupMemberCommandHandler: SignupMemberCommandHandler,
        loginMemberCommandHandler: LoginMemberCommandHandler,
        issueTemporaryPasswordCommandHandler: IssueTemporaryPasswordCommandHandler,
        changeMemberPasswordCommandHandler: ChangeMemberPasswordCommandHandler,
        createSeatHoldCommandHandler: CreateSeatHoldCommandHandler,
        releaseSeatHoldCommandHandler: ReleaseSeatHoldCommandHandler,
        requestPaymentCommandHandler: RequestPaymentCommandHandler,
        handlePaymentCallbackCommandHandler: HandlePaymentCallbackCommandHandler,
        refundPaymentCommandHandler: RefundPaymentCommandHandler,
      ) =>
        CommandBus.of([
          { command: RequestPhoneVerificationCommand, handler: requestPhoneVerificationCommandHandler },
          { command: ConfirmPhoneVerificationCommand, handler: confirmPhoneVerificationCommandHandler },
          { command: SignupMemberCommand, handler: signupMemberCommandHandler },
          { command: LoginMemberCommand, handler: loginMemberCommandHandler },
          { command: IssueTemporaryPasswordCommand, handler: issueTemporaryPasswordCommandHandler },
          { command: ChangeMemberPasswordCommand, handler: changeMemberPasswordCommandHandler },
          { command: CreateSeatHoldCommand, handler: createSeatHoldCommandHandler },
          { command: ReleaseSeatHoldCommand, handler: releaseSeatHoldCommandHandler },
          { command: RequestPaymentCommand, handler: requestPaymentCommandHandler },
          { command: HandlePaymentCallbackCommand, handler: handlePaymentCallbackCommandHandler },
          { command: RefundPaymentCommand, handler: refundPaymentCommandHandler },
        ]),
      inject: [
        RequestPhoneVerificationCommandHandler,
        ConfirmPhoneVerificationCommandHandler,
        SignupMemberCommandHandler,
        LoginMemberCommandHandler,
        IssueTemporaryPasswordCommandHandler,
        ChangeMemberPasswordCommandHandler,
        CreateSeatHoldCommandHandler,
        ReleaseSeatHoldCommandHandler,
        RequestPaymentCommandHandler,
        HandlePaymentCallbackCommandHandler,
        RefundPaymentCommandHandler,
      ],
    },
  ],
  exports: [CommandBus],
})
export class CommandModule {}
